import json
from pathlib import Path

import numpy as np
from nicegui import ui
from scipy.interpolate import interp1d

# --- Course Configuration ---

EXAM_COURSES = [
    {
        'route': '/math1014mt',
        'nav_label': 'MATH1014 MT',
        'title': 'MATH1014 Midterm',
        'subtitle': '1192 students',
        'label': 'Enter your midterm score',
        'placeholder': '0-100',
        'total_students': 1192,
        'bin_counts': [0, 22, 61, 132, 151, 159, 201, 180, 163, 91, 32],
        'score_step': 10,
        'interp_step': 1,
    },
    {
        'route': '/math1014fn',
        'nav_label': 'MATH1014 FN',
        'title': 'MATH1014 Final',
        'subtitle': '1192 students',
        'label': 'Enter your final score',
        'placeholder': '0-100',
        'total_students': 1192,
        'bin_counts': [0, 2, 12, 9, 25, 40, 24, 48, 44, 59, 68, 70, 94, 81, 107, 96, 120, 84, 71, 63, 49],
        'score_step': 5,
        'interp_step': 1,
    },
    {
        'route': '/comp2012hmt',
        'nav_label': 'COMP2012H MT',
        'title': 'COMP2012H Midterm',
        'subtitle': '53 students \u2022 0.25 increment',
        'label': 'Enter your midterm score',
        'placeholder': 'e.g. 75',
        'total_students': 53,
        'bin_counts': [0, 0, 0, 0, 0, 1, 1, 1, 1, 3, 3, 5, 3, 2, 13, 6.5, 1.5, 4.5, 4.5, 1.5, 1.5],
        'score_step': 5,
        'interp_step': 0.25,
    },
]


def compute_percentiles(bin_counts, score_step, interp_step, max_score=100):
    """Compute linear and cubic interpolation percentile curves from histogram bin counts."""
    counts = np.array(bin_counts)
    cumulative = np.cumsum(counts)
    scores = np.arange(0, max_score + score_step, score_step)
    interp_points = np.arange(0, max_score + interp_step, interp_step)

    linear = np.interp(interp_points, scores, cumulative)
    linear_pct = list(1 - linear / np.max(linear))

    f_cubic = interp1d(scores, cumulative, kind='cubic')
    cubic = f_cubic(interp_points)
    cubic_pct = list(1 - cubic / np.max(cubic))

    return linear_pct, cubic_pct


# Pre-compute percentile curves at startup
for _course in EXAM_COURSES:
    _linear, _cubic = compute_percentiles(
        _course['bin_counts'], _course['score_step'], _course['interp_step'],
    )
    _course['linear'] = _linear
    _course['cubic'] = _cubic

# GPA ranking data (generated by analyzer.py from PDF)
_HERE = Path(__file__).parent
with open(_HERE / 'data_output.json') as f:
    rank720 = sorted([x[1] for x in json.load(f)], reverse=True)


# --- Helpers ---

def count_run(lst, start, value, step=1):
    """Count consecutive occurrences of value in lst starting at start index."""
    count = 0
    i = start
    while 0 <= i < len(lst) and lst[i] == value:
        count += 1
        i += step
    return count


def format_rank(top, bottom, total):
    return f'{top}-{bottom}/{total}' if top != bottom else f'{top}/{total}'


# --- Shared UI ---

def dark_page_setup():
    ui.dark_mode(True)
    ui.query('body').classes('bg-gray-950')
    ui.query('.nicegui-content').classes('p-0 gap-0')


def page_header(title, subtitle=None):
    with ui.column().classes(
        'w-full items-center py-10 px-4 mb-8 '
        'bg-gradient-to-br from-gray-900 via-gray-900 to-cyan-950 border-b border-cyan-500/30'
    ):
        ui.label(title).classes('text-4xl font-bold text-cyan-400 tracking-tight')
        if subtitle:
            ui.label(subtitle).classes('text-gray-400 text-lg mt-1')


def nav_bar():
    items = [('GPA Rank', '/')] + [(str(c['nav_label']), str(c['route'])) for c in EXAM_COURSES]
    with ui.row().classes('w-full max-w-2xl mx-auto gap-2 flex-wrap justify-center mb-6'):
        for label, href in items:
            ui.link(label, href).classes(
                'px-4 py-2 rounded-full bg-cyan-950 text-cyan-400 border border-cyan-500/30 '
                'hover:bg-cyan-900 hover:border-cyan-400 font-medium text-sm no-underline transition-colors'
            )


# --- GPA Rank Page ---

@ui.page('/')
async def gpa_page():
    total = len(rank720)

    def range_check(value):
        if value is None:
            return False
        return 0 <= round(value * 720) <= 3096

    def update_results(e):
        if e.value is None:
            return
        r720 = round(e.value * 720)
        result.set_text(f'{r720}/720')
        result2.set_text(f'{r720/720:.8f}')

        if r720 in rank720:
            idx = rank720.index(r720)
            run = count_run(rank720, idx, r720)
            rank_range_top = idx + 1
            rank_range_bottom = idx + run
            rank_at_u.set_text(format_rank(rank_range_top, rank_range_bottom, total))
        else:
            for i in range(total):
                if rank720[i] < r720:
                    rank_range_top = i + 1
                    rank_range_bottom = i
                    break
            else:
                rank_range_top = total
                rank_range_bottom = total - 1
            rank_at_u.set_text(f'Between {rank_range_bottom} and {rank_range_top} / {total}')

        if rank_range_bottom == total:
            rank_after_u.set_text('You are truly the worst!')
        else:
            val = rank720[rank_range_bottom]
            run = count_run(rank720, rank_range_bottom, val)
            rank_after_u.set_text(
                f'{val/720:.6f} @ {format_rank(rank_range_bottom + 1, rank_range_bottom + run, total)}')

        if rank_range_top == 1:
            rank_before_u.set_text('You are truly the best!')
        else:
            val = rank720[rank_range_top - 2]
            run = count_run(rank720, rank_range_top - 2, val, step=-1)
            rank_before_u.set_text(
                f'{val/720:.6f} @ {format_rank(rank_range_top - run, rank_range_top - 1, total)}')

        results_card.set_visibility(True)

    def is_filled(value):
        if value is not None:
            return True
        for elem in (result, result2, rank_before_u, rank_at_u, rank_after_u):
            elem.set_text('')
        results_card.set_visibility(False)
        return False

    dark_page_setup()
    page_header('Project Ordinal', 'SENG Y1 GPA Rank Lookup')
    nav_bar()

    with ui.column().classes('w-full max-w-2xl mx-auto px-4'):
        with ui.card().classes('w-full p-8 rounded-2xl bg-gray-900 border border-gray-800'):
            ui.label('Enter your GPA').classes('text-lg font-semibold text-cyan-400 mb-2')
            ui.label('Fall 2022 cohort \u2022 852 students').classes('text-sm text-gray-500 mb-4')
            ui.number(label='GPA', placeholder='e.g. 3.500',
                      on_change=update_results,
                      validation={'Empty input': is_filled, 'Out of range': range_check},
                      ).classes('w-full text-lg')

        results_card = ui.card().classes('w-full p-8 rounded-2xl mt-4 bg-gray-900 border border-gray-800')
        results_card.set_visibility(False)
        with results_card:
            ui.label('Results').classes('text-lg font-semibold text-cyan-400 mb-4')

            with ui.grid(columns=2).classes('w-full gap-4'):
                with ui.column().classes('bg-cyan-950/50 rounded-xl p-4 border border-cyan-500/20'):
                    ui.label('GPA Fraction').classes('text-xs font-medium text-cyan-500 uppercase tracking-wide')
                    result = ui.label().classes('text-2xl font-bold text-cyan-300')
                with ui.column().classes('bg-cyan-950/50 rounded-xl p-4 border border-cyan-500/20'):
                    ui.label('GPA Score').classes('text-xs font-medium text-cyan-500 uppercase tracking-wide')
                    result2 = ui.label().classes('text-2xl font-bold text-cyan-300')

            ui.separator().classes('my-4')

            with ui.grid(columns=3).classes('w-full gap-4'):
                with ui.column().classes('bg-emerald-950/40 rounded-xl p-4 items-center border border-emerald-500/20'):
                    ui.label('Rank Above').classes('text-xs font-medium text-emerald-400 uppercase tracking-wide')
                    rank_before_u = ui.label().classes('text-sm font-semibold text-emerald-300 text-center')
                with ui.column().classes('bg-cyan-950/60 rounded-xl p-4 items-center border border-cyan-400/40'):
                    ui.label('Your Rank').classes('text-xs font-medium text-cyan-400 uppercase tracking-wide')
                    rank_at_u = ui.label().classes('text-xl font-bold text-cyan-300 text-center')
                with ui.column().classes('bg-rose-950/40 rounded-xl p-4 items-center border border-rose-500/20'):
                    ui.label('Rank Below').classes('text-xs font-medium text-rose-400 uppercase tracking-wide')
                    rank_after_u = ui.label().classes('text-sm font-semibold text-rose-300 text-center')


# --- Exam Score Pages ---

def exam_page(course):
    data_linear = course['linear']
    data_cubic = course['cubic']
    total_students = course['total_students']
    interp_step = course['interp_step']

    def update_results(e):
        if e.value is None:
            return
        try:
            idx = int(e.value / interp_step)
            pct_disp.set_text(f'Top {data_linear[idx] * 100:.2f}%')
            stud_disp.set_text(f'{data_linear[idx] * total_students:.0f} / {total_students}')
        except Exception:
            pct_disp.set_text('-')
            stud_disp.set_text('')
        try:
            idx = int(e.value / interp_step)
            pct_disp_2.set_text(f'Top {data_cubic[idx] * 100:.2f}%')
            stud_disp_2.set_text(f'{data_cubic[idx] * total_students:.0f} / {total_students}')
        except Exception:
            pct_disp_2.set_text('-')
            stud_disp_2.set_text('')
        results_card.set_visibility(True)

    dark_page_setup()
    page_header('Project Ordinal', course['title'])
    nav_bar()

    with ui.column().classes('w-full max-w-2xl mx-auto px-4'):
        with ui.card().classes('w-full p-8 rounded-2xl bg-gray-900 border border-gray-800'):
            ui.label(course['label']).classes('text-lg font-semibold text-cyan-400 mb-2')
            ui.label(course['subtitle']).classes('text-sm text-gray-500 mb-4')
            ui.number(label='Score', placeholder=course['placeholder'],
                      on_change=update_results).classes('w-full text-lg')

        results_card = ui.card().classes('w-full p-8 rounded-2xl mt-4 bg-gray-900 border border-gray-800')
        results_card.set_visibility(False)
        with results_card:
            ui.label('Results').classes('text-lg font-semibold text-cyan-400 mb-4')
            with ui.grid(columns=2).classes('w-full gap-6'):
                with ui.column().classes('bg-cyan-950/50 rounded-xl p-5 border border-cyan-500/20'):
                    ui.label('Linear Interpolation').classes('text-xs font-medium text-cyan-500 uppercase tracking-wide mb-2')
                    pct_disp = ui.label().classes('text-2xl font-bold text-cyan-300')
                    stud_disp = ui.label().classes('text-sm text-cyan-600 mt-1')
                with ui.column().classes('bg-teal-950/50 rounded-xl p-5 border border-teal-500/20'):
                    ui.label('Cubic Interpolation').classes('text-xs font-medium text-teal-500 uppercase tracking-wide mb-2')
                    pct_disp_2 = ui.label().classes('text-2xl font-bold text-teal-300')
                    stud_disp_2 = ui.label().classes('text-sm text-teal-600 mt-1')


# Register exam pages dynamically from EXAM_COURSES
for _course in EXAM_COURSES:
    def _make_page(c):
        @ui.page(c['route'])
        async def _page():
            exam_page(c)
    _make_page(_course)


ui.run(title='Project Ordinal')
